projetISI/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GroupeController;
use App\Http\Controllers\ChanteurController;
use App\Http\Controllers\MusiqueController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[GroupeController::class,'index']);

Route::get('/dashboard', function () {
    return redirect('/groupes');
});

Route::resource('groupes', GroupeController::class);
Route::resource('chanteurs', ChanteurController::class);
Route::resource('musiques', MusiqueController::class);

require __DIR__.'/auth.php';

projetISI/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

projetISI/resources/views/chanteurs.blade.php
@extends('layouts.layout')

@section('titrePage')
    Chanteurs
@endsection

@section('titreItem')
    <h1>{{$groupe->nom_groupe}} </h1>
@endsection

@section('contenu')

    <body>
        <div class="chanteurs">
            @foreach($chanteurs as $chanteur)
                            <div class="cadre"> 
                                <span>{{$chanteur->nom_reel}} </span><br>
                                <span>{{$chanteur->nationalite}} </span><br>
                                <span>{{$chanteur->date_naissance}}</span><br>
                                <?php echo '<img src="../images/'.$chanteur->photo.'" class="card-img-top">';?>
                            </div>
                    <h3 class="name">{{ $chanteur->nom_de_scene }}</h3>
            @endforeach
        </div>

        <div class="mti">
            @foreach($musiques as $musique)
            <a href="{{ route('musiques.show', $musique->id) }}">
                <div class="musiques">
                    <div class="titre">
                        <p> {{ $musique->titre}} </p>
                    </div>
                    <div class="annee">
                        <p> {{ $musique->annee_de_sortie}} </p>
                    </div>
                </div>
            </a>
            @endforeach
        </div>

        <br>

        @auth
        <div class="cbtt">
            <a href="{{route('musiques.create')}}" class="btt">
                Ajouter une musique 
            </a>
        </div>
        @else
        @endauth

        <br>
        
    </body>
@endsection

projetISI/resources/views/confirm.blade.php
@extends('layouts.layout')

@section('titrePage')
    Confirmation
@endsection


@section('contenu')
    <h3>La musique a bien été ajoutée.</h3>
@endsection

projetISI/resources/views/create.blade.php
@extends('layouts.layout')

@section('titrePage')
    Ajout d'une musique
@endsection

@section('contenu')
<body>
    <div class = "container">
        <div class ="row card text-white bg-dark">
            <h4 class ="card-header"> Ajouter une musique </h4>
            <div class ="card-body">
                <form action="{{route('musiques.store')}}" method="POST">
                    @csrf
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control @error('titre') is-invalid @enderror" name="titre" id="titre" placeholder="Titre de la musique">
                        @error('titre')
                            <div class="alert alert-danger">{{$message}}</div>
                        @enderror
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control @error('lien_musique') is-invalid @enderror" name="lien_musique" id="lien_musique" placeholder="Lien de la musique">
                        @error('lien_musique')
                            <div class="alert alert-danger">{{$message}}</div>
                        @enderror
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control @error('album') is-invalid @enderror" name="album" id="album" placeholder="Album de la musique">
                        @error('album')
                            <div class="alert alert-danger">{{$message}}</div>
                        @enderror
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control @error('annee_de_sortie') is-invalid @enderror" name="annee_de_sortie" id="annee_de_sortie" placeholder="Année de sortie de la musique">
                        @error('annee_de_sortie')
                            <div class="alert alert-danger">{{$message}}</div>
                        @enderror
                    </div>
                    <br>
                    <div class="form-group">
                        <select type="text" class="form-control @error('groupe_id') is-invalid @enderror" name="groupe_id" id="groupe_id">
                            <option value="1">BlackPink</option>
                            <option value="2">Twice</option>
                            <option value="3">Red Velvet</option>
                            <option value="4">Aespa</option>
                            <option value="5">IVE</option>
                            <option value="6">Weki Meki</option>
                            <option value="7">(G)I-DLE</option>
                        </select>
                        @error('groupe_id') 
                            <div class="alert alert-danger">{{$message}}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-secondary"> Envoyer</button>
                </form>
                
            </div>
        </div>
    </div>
</body>
@endsection

projetISI/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

projetISI/resources/views/edit.blade.php
@extends('layouts.layout')

@section('titrePage')
    Modification d'une musique
@endsection

@section('contenu')
<body>
    <div class = "container">
        <div class ="row card text-white bg-dark">
            <h4 class ="card-header"> Modifier une musique </h4>
            <div class ="card-body">
                <form action="{{route('musiques.update', $musique->id)}}" method="POST">
                    @csrf
                    @method('put')
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control @error('lien_musique') is-invalid @enderror" name="lien_musique" id="lien_musique" placeholder="Lien de la musique">
                        @error('lien_musique')
                            <div class="alert alert-danger">{{$message}}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-secondary"> Envoyer</button>
                </form>
                
            </div>
        </div>
    </div>
</body>
@endsection

projetISI/resources/views/index.blade.php
@extends('layouts.layout')

@section('titrePage')
    Accueil
@endsection

@section('titreItem')
    <h1>Groupes </h1>
@endsection

@section('contenu')

    <body>
        <div class="groupe">
            @foreach($groupes as $groupe)
            <a href="{{ route('groupes.show', $groupe->id) }}"><h1> {{ $groupe->nom_groupe }} </h1></a>
                <a href="{{ route('groupes.show', $groupe->id) }}">
                    <div class=image>
                        <?php echo '<img class="mg" src="images/'.$groupe->photo_groupe.'">';?>
                    </div>
                </a><br>
            @endforeach
        </div>
    </body>
       
@endsection

projetISI/resources/views/musique.blade.php
@extends('layouts.layout')

@section('titrePage')
    Musique
@endsection

@section('titreItem')
    <h1>{{$musique->titre}}</h1>
@endsection

@section('contenu')
    <body>
        @auth
        <div class="video-responsive"><iframe width="1200" height="600" src={{ $musique ->lien_musique}} allowfullscreen></iframe></div>
        <h3>Album : {{ $musique ->album}}, Année de sortie : {{ $musique ->annee_de_sortie}}</h3>
        <br>
        <div class="cbtt">
            <a href="{{route('musiques.edit', $musique->id)}}" class="btt">
                Modifier le lien
            </a>
        </div>
        <div class="cbtt">
            <a href="{{route('musiques.create')}}" class="btt">
                Ajouter une musique 
            </a>
        </div>
        <br>
        @else
        <a href="{{ route('login')}}"><h3>Il faut se connecter pour accéder à ce contenu</h3></a>
        @endauth
    </body>
@endsection